tags:
- name: meals
  description: meals API

paths:
# [GET] meals
  /users:
    get:
      tags:
      - meals
      summary: Find All Meals
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# definitions
definitions:
  meals:
    type: object
    required:
        - name
        - price
        - description
    properties:
      price:
        type: number
        description: Meal Price
      description:
        type: string
        description: Meal Description

schemes:
 - http
